/*M///////////////////////////////////////////////////////////////////////////////////////
//
//  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
//
//  By downloading, copying, installing or using the software you agree to this license.
//  If you do not agree to this license, do not download, install,
//  copy or use the software.
//
//
//                           License Agreement
//                For Open Source Computer Vision Library
//
<<<<<<< HEAD
<<<<<<< HEAD:photoManagement/opencv/include/opencv2/ximgproc/brightedges.hpp
// Copyright (C) 2017, IBM Corporation, all rights reserved.
=======
// Copyright (C) 2010-2013, Advanced Micro Devices, Inc., all rights reserved.
>>>>>>> refs/remotes/origin/master:photoManagement/opencv/include/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
=======
// Copyright (C) 2017, IBM Corporation, all rights reserved.
>>>>>>> refs/remotes/origin/master
// Third party copyrights are property of their respective owners.
//
// @Authors
//      Marc Fiammante marc.fiammante@fr.ibm.com
//
// Redistribution and use in source and binary forms, with or without modification,
// are permitted provided that the following conditions are met:
//
//   * Redistribution's of source code must retain the above copyright notice,
//     this list of conditions and the following disclaimer.
//
//   * Redistribution's in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//
<<<<<<< HEAD
<<<<<<< HEAD:photoManagement/opencv/include/opencv2/ximgproc/brightedges.hpp
//   * The name of OpenCV Foundation or contributors may not be used to endorse or promote products
=======
//   * The name of the copyright holders may not be used to endorse or promote products
>>>>>>> refs/remotes/origin/master:photoManagement/opencv/include/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
=======
//   * The name of OpenCV Foundation or contributors may not be used to endorse or promote products
>>>>>>> refs/remotes/origin/master
//     derived from this software without specific prior written permission.
//
// This software is provided by the copyright holders and contributors "as is" and
// any express or implied warranties, including, but not limited to, the implied
// warranties of merchantability and fitness for a particular purpose are disclaimed.
// In no event shall the OpenCV Foundation or contributors be liable for any direct,
// indirect, incidental, special, exemplary, or consequential damages
// (including, but not limited to, procurement of substitute goods or services;
// loss of use, data, or profits; or business interruption) however caused
// and on any theory of liability, whether in contract, strict liability,
// or tort (including negligence or otherwise) arising in any way out of
// the use of this software, even if advised of the possibility of such damage.
//
//M*/
<<<<<<< HEAD
<<<<<<< HEAD:photoManagement/opencv/include/opencv2/ximgproc/brightedges.hpp
=======
>>>>>>> refs/remotes/origin/master
#include "opencv2/core.hpp"
namespace cv
{
    namespace ximgproc {
        CV_EXPORTS_W void  BrightEdges(Mat &_original, Mat &_edgeview, int contrast = 1, int shortrange = 3, int longrange = 9);
    }
<<<<<<< HEAD
}
=======

#ifndef OPENCV_CORE_OCL_RUNTIME_OPENCL_WRAPPERS_HPP
#define OPENCV_CORE_OCL_RUNTIME_OPENCL_WRAPPERS_HPP

#include "autogenerated/opencl_core_wrappers.hpp"

#endif // OPENCV_CORE_OCL_RUNTIME_OPENCL_WRAPPERS_HPP
>>>>>>> refs/remotes/origin/master:photoManagement/opencv/include/opencv2/core/opencl/runtime/opencl_core_wrappers.hpp
=======
}
>>>>>>> refs/remotes/origin/master
